[bell]
animation = "Ease"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#18d411"
blue = "#4b7edb"
cyan = "#ff3e3e"
green = "#f53434"
magenta = "#26b326"
red = "#c62828"
white = "#e4cccc"
yellow = "#310303"

[colors.normal]
black = "#160000"
blue = "#5b2d17"
cyan = "#8e3434"
green = "#db5a5a"
magenta = "#0f8c18"
red = "#e10707"
white = "#ffa100"
yellow = "#d54949"

[colors.primary]
background = "#000000"
foreground = "#ffdfdf"

[cursor]
blink_interval = 270
blink_timeout = 0

[cursor.style]
blinking = "On"
shape = "Block"

[env]
COLORTERM = "truecolor"
TERM = "xterm-256color"

[font]
size = 16

[font.bold]
family = "Inconsolata LGC Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "Inconsolata LGC Nerd Font Mono"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Inconsolata LGC Nerd Font Mono"
style = "Italic"

[font.normal]
family = "Inconsolata LGC Nerd Font Mono"
style = "Regular"

[font.offset]
x = 0
y = 0

[[hints.enabled]]
command = "open"
hyperlinks = true
regex = "(mailto:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\" {-}\\\\^⟨⟩`]+"

[hints.enabled.mouse]
enabled = true
mods = "Command"

[[keyboard.bindings]]
action = "Minimize"
key = "N"
mods = "Command| Alt"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[[keyboard.bindings]]
chars = "\u0015"
key = "Back"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u0017"
key = "Back"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0002d"
key = "D"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002s"
key = "S"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002q"
key = "Q"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = """
./session.sh
"""
key = "N"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = """
reset
"""
key = "R"
mods = "Control|Alt"

[[keyboard.bindings]]
chars = """
nvim
"""
key = "\\"
mods = "Alt"

[[keyboard.bindings]]
chars = "nvim "
key = "G"
mods = "Control|Alt"

[[keyboard.bindings]]
chars = """
tmux new-session
"""
key = "N"
mods = "Control"

[[keyboard.bindings]]
chars = """
tmux ls; read -p 'Attach to ID: ' ID; tmux attach -t $ID
"""
key = "A"
mods = "Command|Shift"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "V"
mods = "Control|Alt"

[[keyboard.bindings]]
chars = "\u0002c"
key = "T"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u0002x"
key = "X"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u0002,"
key = "R"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u0002p"
key = "LBracket"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002n"
key = "RBracket"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00020"
key = "Key0"
mods = "Control|Alt"

[[keyboard.bindings]]
chars = "\u00021"
key = "Key1"
mods = "Control|Alt"

[[keyboard.bindings]]
chars = "\u00022"
key = "Key2"
mods = "Control|Alt"

[[keyboard.bindings]]
chars = "\u00023"
key = "Key3"
mods = "Control|Alt"

[[keyboard.bindings]]
chars = "\u00024"
key = "Key4"
mods = "Control|Alt"

[[keyboard.bindings]]
chars = "\u00025"
key = "Key5"
mods = "Control|Alt"

[[keyboard.bindings]]
chars = "\u00026"
key = "Key6"
mods = "Control|Alt"

[[keyboard.bindings]]
chars = "\u00027"
key = "Key7"
mods = "Control|Alt"

[[keyboard.bindings]]
chars = "\u00028"
key = "Key8"
mods = "Control|Alt"

[[keyboard.bindings]]
chars = "\u00029"
key = "Key9"
mods = "Control|Alt"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "Home"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"
mode = "~Alt"
mods = "Shift"

[mouse]
hide_when_typing = true

[window]
# decorations = "full"
decorations = "none"
opacity = 1
dynamic_padding = true

[window.dimensions]
columns = 218
lines = 65

[window.padding]
x = 6
y = 4
