os:
  editPreset: "nvim"
gui:
  theme:
    activeBorderColor:
      - "#e02840"
      - bold
    inactiveBorderColor:
      - "#555555"
    searchingActiveBorderColor:
      - "#d79921"
      - bold
    optionsTextColor:
      - "#a89984"
    selectedLineBgColor:
      - "#1a1a1a"
    cherryPickedCommitFgColor:
      - "#ebdbb2"
    cherryPickedCommitBgColor:
      - "#458588"
    markedBaseCommitFgColor:
      - "#ebdbb2"
    markedBaseCommitBgColor:
      - "#b16286"
    unstagedChangesColor:
      - "#cc241d"
    defaultFgColor:
      - "#ebdbb2"
  authorColors:
    "*": "#689d6a"
git:
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never --features custom-theme
