$background = 070e1b
$onBackground = dae6ff
$surface = 070e1b
$surfaceDim = 070e1b
$surfaceBright = 1a2c48
$surfaceContainerLowest = 000000
$surfaceContainerLow = 0a1423
$surfaceContainer = 0e1a2c
$surfaceContainerHigh = 122035
$surfaceContainerHighest = 16263e
$onSurface = dae6ff
$surfaceVariant = 16263e
$onSurfaceVariant = 9cacca
$outline = 677692
$outlineVariant = 394863
$inverseSurface = f9f9ff
$inverseOnSurface = 4e5565
$shadow = 000000
$scrim = 000000
$surfaceTint = b6d7ff
$primary = b6d7ff
$primaryDim = 9ecafc
$onPrimary = 194c77
$primaryContainer = 9ecafc
$onPrimaryContainer = 0a436d
$inversePrimary = 34628e
$primaryFixed = 9ecafc
$primaryFixedDim = 91bcee
$onPrimaryFixed = 002e4f
$onPrimaryFixedVariant = 194c77
$secondary = dfbecd
$secondaryDim = d0b0bf
$onSecondary = 513945
$secondaryContainer = 341f2b
$onSecondaryContainer = bb9baa
$secondaryFixed = ffdcec
$secondaryFixedDim = f0cedd
$onSecondaryFixed = 523a46
$onSecondaryFixedVariant = 705663
$tertiary = ffafd2
$tertiaryDim = f38ebd
$onTertiary = 70224c
$tertiaryContainer = ff99c8
$onTertiaryContainer = 641843
$tertiaryFixed = ff99c8
$tertiaryFixedDim = f08cba
$onTertiaryFixed = 46002b
$onTertiaryFixedVariant = 6f214c
$error = ff716c
$errorDim = c94947
$onError = 490006
$errorContainer = 8a1a1e
$onErrorContainer = ff9993
$primaryPaletteKeyColor = 4e7aa8
$secondaryPaletteKeyColor = 8b6f7d
$tertiaryPaletteKeyColor = b35985
$neutralPaletteKeyColor = 6f7787
$neutralVariantPaletteKeyColor = 5e78a4
$errorPaletteKeyColor = cc4b49
$primary_paletteKeyColor = 4e7aa8
$secondary_paletteKeyColor = 8b6f7d
$tertiary_paletteKeyColor = b35985
$neutral_paletteKeyColor = 6f7787
$neutral_variant_paletteKeyColor = 5e78a4
$term0 = 343434
$term1 = 8383ff
$term2 = 44def5
$term3 = 75fcdd
$term4 = 85afd0
$term5 = 92a8ef
$term6 = 8ed2f5
$term7 = ccdcd6
$term8 = ac9fa9
$term9 = a29eff
$term10 = 89ecff
$term11 = c9fff3
$term12 = aac4d7
$term13 = aebcf8
$term14 = ace3ff
$term15 = ffffff
$rosewater = f4f0fa
$flamingo = dfe0f5
$pink = d2dcff
$mauve = a0c1ff
$red = 9cb0ff
$maroon = b1bcf1
$peach = e0c2f9
$yellow = d0f9f4
$green = bae6ff
$teal = c1e4ff
$sky = bcdfff
$sapphire = 97ccff
$blue = 8bc0ff
$lavender = aecfff
$klink = 468cca
$klinkSelection = 458cca
$kvisited = 4a7fdb
$kvisitedSelection = 497fdb
$knegative = 607dff
$knegativeSelection = 607eff
$kneutral = c794ff
$kneutralSelection = c794ff
$kpositive = 00b6ef
$kpositiveSelection = 00b6ef
$text = dae6ff
$subtext1 = 9cacca
$subtext0 = 677692
$overlay2 = 596781
$overlay1 = 4b586f
$overlay0 = 3e495e
$surface2 = 313b4e
$surface1 = 242d3e
$surface0 = 151d2c
$base = 070e1b
$mantle = 070e1b
$crust = 070d1a
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
